# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : CampaignExportService
Operation: addJob
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/6.5/docs/en/api_reference/services/CampaignExportService.md

Generated by 'api_reference_example_generator.py' using code template 'sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'CampaignExportService'
OPERATION = 'addJob'
OPERAND = {
  "setting": {
    "accountId": "SAMPLE-ACCOUNT-ID", 
    "campaignUserStatuses": "ACTIVE", 
    "adGroupUserStatuses": "ACTIVE", 
    "adGroupAdUserStatuses": "ACTIVE", 
    "adGroupCriterionUserStatuses": "ACTIVE", 
    "adGroupAdApprovalStatuses": [
      "APPROVED", 
      "APPROVED_WITH_REVIEW", 
      "REVIEW", 
      "PRE_DISAPPROVED", 
      "POST_DISAPPROVED"
    ], 
    "adGroupCriterionApprovalStatuses": [
      "APPROVED", 
      "APPROVED_WITH_REVIEW", 
      "REVIEW", 
      "PRE_DISAPPROVED", 
      "POST_DISAPPROVED"
    ], 
    "entityTypes": "ALL", 
    "jobName": "DownloadJob", 
    "lang": "JA", 
    "output": "CSV", 
    "encoding": "SJIS", 
    "exportFields": [
      "CAMPAIGN_NAME", 
      "AD_GROUP_NAME"
    ]
  }
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "values": {
      "operationSucceeded": "true", 
      "job": {
        "accountId": "SAMPLE-ACCOUNT-ID", 
        "jobId": "42", 
        "jobName": "DownloadJob", 
        "userName": "8983-5689-9971-5970", 
        "startDate": "2011-09-07T22:55:37+09:00", 
        "status": "IN_PROGRESS", 
        "progress": "0", 
        "exportFields": [
          "CAMPAIGN_NAME", 
          "AD_GROUP_NAME"
        ]
      }
    }
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
