# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : CampaignExportService
Operation: get
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/201901/docs/en/api_reference/services/CampaignExportService.md

Generated by 'api_reference_example_generator.py' using code template 'examples/sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'CampaignExportService'
OPERATION = 'get'
OPERAND = {
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "jobIds": [
    "1111", 
    "1112"
  ], 
  "statuses": [
    "SYSTEM_ERROR", 
    "COMPLETED", 
    "IN_PROGRESS", 
    "TIMEOUT"
  ], 
  "paging": {
    "startIndex": "1", 
    "numberResults": "10"
  }
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "totalNumEntries": "4", 
    "Page.Type": "CampaignExportPage", 
    "values": [
      {
        "operationSucceeded": "true", 
        "job": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "jobId": "1999", 
          "userName": "2843-2576-6539-6847", 
          "startDate": "2017-11-28T10:31:24+09:00", 
          "endDate": "2017-11-28T10:31:25+09:00", 
          "status": "COMPLETED", 
          "progress": "100", 
          "downloadUrl": "https://ss.yahooapis.jp/export/V201901/download/Cwb66zoaz1qr0HD6DlPq3Xca8LRUODnBWLcEeT64WuhhLrCf507Jo3v5FmZ6fGvm3k0YqbjOu9XBqkkZVCBWrhb0wtuAuxVbg35S_HPGxfCg9gxq5qabtwPblcRmp7LzlvEedZzaczG.g7wrgliey93KdGob8adSnhGNol0PZfJ8UBeAaBJ7zjjS010XmqJe8u0XMYpS7DqKlFe4REWkLAX293y8E1hUhRckDiul3awJBlqAQdnR9s2BRmMsznRPMxp85v2OXQm_onO79tN6lY7CXWNOzd3enyxllUXPmAwL4Ey8ciV01Ku3cBYh08RiIqBwV5TDJf4-", 
          "exportFields": [
            "CAMPAIGN_NAME", 
            "AD_GROUP_NAME", 
            "AD_NAME"
          ]
        }
      }, 
      {
        "operationSucceeded": "true", 
        "job": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "jobId": "1998", 
          "userName": "2843-2576-6539-6847", 
          "startDate": "2017-11-28T10:31:24+09:00", 
          "status": "IN_PROGRESS", 
          "progress": "20", 
          "exportFields": [
            "CAMPAIGN_NAME", 
            "AD_GROUP_NAME", 
            "AD_NAME"
          ]
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
