# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : CampaignService
Operation: mutate (REMOVE)
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/6.5/docs/en/api_reference/services/CampaignService.md

Generated by 'api_reference_example_generator.py' using code template 'sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'CampaignService'
OPERATION = 'mutate (REMOVE)'
OPERAND = {
  "operator": "REMOVE", 
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "operand": [
    {
      "campaignId": "SAMPLE-CAMPAIN-ID"
    }, 
    {
      "campaignId": "SAMPLE-CAMPAIN-ID"
    }, 
    {
      "campaignId": "SAMPLE-CAMPAIN-ID"
    }
  ]
}

"""
SAMPLE RESPONSE = {
  "@xmlns": "http://ss.yahooapis.jp/V70", 
  "@xmlns:ns2": "http://ss.yahooapis.jp/V70/Campaign", 
  "rval": {
    "ListReturnValue.Type": "CampaignReturnValue", 
    "Operation.Type": "REMOVE", 
    "values": [
      {
        "operationSucceeded": "true", 
        "campaign": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "campaignId": "SAMPLE-CAMPAIN-ID", 
          "campaignTrackId": "100000001", 
          "campaignName": "set Standard Campaign with TargetSpendBiddingScheme.", 
          "userStatus": "ACTIVE", 
          "servingStatus": "SERVING", 
          "startDate": "20170101", 
          "endDate": "20301231", 
          "budget": {
            "period": "DAILY", 
            "amount": "20000", 
            "deliveryMethod": "STANDARD"
          }, 
          "biddingStrategyConfiguration": {
            "biddingStrategyId": "20001", 
            "biddingStrategyName": "TargetSpendBiddingScheme.", 
            "biddingStrategyType": "TARGET_SPEND", 
            "biddingStrategySource": "CAMPAIGN", 
            "biddingScheme": {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "TargetSpendBiddingScheme", 
              "biddingStrategyType": "TARGET_SPEND", 
              "bidCeiling": "50000", 
              "spendTarget": "0"
            }
          }, 
          "conversionOptimizerEligibility": "DISABLE", 
          "adServingOptimizationStatus": "ROTATE_INDEFINITELY", 
          "settings": [
            {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "GeoTargetTypeSetting", 
              "type": "GEO_TARGET_TYPE_SETTING", 
              "positiveGeoTargetType": "DONT_CARE", 
              "negativeGeoTargetType": "DONT_CARE"
            }, 
            {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "TargetingSetting", 
              "type": "TARGET_LIST_SETTING", 
              "targetAll": "DEACTIVE"
            }
          ], 
          "campaignType": "STANDARD", 
          "trackingUrl": "http://yahoo.co.jp?url={lpurl}&c={campaignid}&g={adgroupid}&a={creative}&type={_site}&pid={_id1}&vid={_id2}", 
          "customParameters": {
            "parameters": [
              {
                "key": "site", 
                "value": "yahoo"
              }, 
              {
                "key": "id1", 
                "value": "1234"
              }, 
              {
                "key": "id2", 
                "value": "a7h59A98yu"
              }
            ]
          }, 
          "urlReviewData": {
            "urlApprovalStatus": "APPROVED"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "campaign": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "campaignId": "SAMPLE-CAMPAIN-ID", 
          "campaignTrackId": "100000002", 
          "campaignName": "set MobileApp(ANDROID) Campaign with PageOnePromotedBiddingScheme.", 
          "userStatus": "ACTIVE", 
          "servingStatus": "SERVING", 
          "startDate": "20170101", 
          "endDate": "20301231", 
          "budget": {
            "period": "DAILY", 
            "amount": "20000", 
            "deliveryMethod": "STANDARD"
          }, 
          "biddingStrategyConfiguration": {
            "biddingStrategyId": "20002", 
            "biddingStrategyName": "PageOnePromotedBiddingScheme.", 
            "biddingStrategyType": "PAGE_ONE_PROMOTED", 
            "biddingStrategySource": "CAMPAIGN", 
            "biddingScheme": {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "PageOnePromotedBiddingScheme", 
              "biddingStrategyType": "PAGE_ONE_PROMOTED", 
              "bidCeiling": "50000", 
              "bidMultiplier": "10.0", 
              "bidChangesForRaisesOnly": "ACTIVE", 
              "raiseBidWhenBudgetConstrained": "DEACTIVE", 
              "raiseBidWhenLowQualityScore": "DEACTIVE"
            }
          }, 
          "conversionOptimizerEligibility": "DISABLE", 
          "adServingOptimizationStatus": "ROTATE_INDEFINITELY", 
          "settings": [
            {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "GeoTargetTypeSetting", 
              "type": "GEO_TARGET_TYPE_SETTING", 
              "positiveGeoTargetType": "DONT_CARE", 
              "negativeGeoTargetType": "DONT_CARE"
            }, 
            {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "TargetingSetting", 
              "type": "TARGET_LIST_SETTING", 
              "targetAll": "DEACTIVE"
            }
          ], 
          "campaignType": "MOBILE_APP", 
          "appStore": "ANDROID", 
          "appId": "201607221800792", 
          "urlReviewData": {
            "urlApprovalStatus": "NONE"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "campaign": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "campaignId": "SAMPLE-CAMPAIN-ID", 
          "campaignTrackId": "100000003", 
          "campaignName": "set MobileApp(IOS) Campaign with ManualCpcBiddingScheme.", 
          "userStatus": "ACTIVE", 
          "servingStatus": "SERVING", 
          "startDate": "20170101", 
          "endDate": "20301231", 
          "budget": {
            "period": "DAILY", 
            "amount": "20000", 
            "deliveryMethod": "STANDARD"
          }, 
          "biddingStrategyConfiguration": {
            "biddingStrategyId": "20003", 
            "biddingStrategyName": "ManualCpcBiddingScheme.", 
            "biddingStrategyType": "MANUAL_CPC", 
            "biddingStrategySource": "CAMPAIGN", 
            "biddingScheme": {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "ManualCpcBiddingScheme", 
              "biddingStrategyType": "MANUAL_CPC"
            }
          }, 
          "conversionOptimizerEligibility": "DISABLE", 
          "adServingOptimizationStatus": "ROTATE_INDEFINITELY", 
          "settings": [
            {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "GeoTargetTypeSetting", 
              "type": "GEO_TARGET_TYPE_SETTING", 
              "positiveGeoTargetType": "DONT_CARE", 
              "negativeGeoTargetType": "DONT_CARE"
            }, 
            {
              "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
              "xsi_type": "TargetingSetting", 
              "type": "TARGET_LIST_SETTING", 
              "targetAll": "DEACTIVE"
            }
          ], 
          "campaignType": "MOBILE_APP", 
          "appStore": "IOS", 
          "appId": "201608188643114", 
          "trackingUrl": "http://yahoo.co.jp?url={lpurl}&c={campaignid}&g={adgroupid}&a={creative}&type={_site}&pid={_id1}&vid={_id2}", 
          "customParameters": {
            "parameters": [
              {
                "key": "site", 
                "value": "yahoo"
              }, 
              {
                "key": "id1", 
                "value": "1234"
              }, 
              {
                "key": "id2", 
                "value": "a7h59A98yu"
              }
            ]
          }, 
          "urlReviewData": {
            "urlApprovalStatus": "APPROVED"
          }
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
