# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : CampaignService
Operation: mutate (SET)
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/6.3/docs/en/api_reference/services/CampaignService.md

Generated by 'api_reference_example_generator.py' using code template 'sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'CampaignService'
OPERATION = 'mutate (SET)'
OPERAND = {
  "operator": "SET", 
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "operand": [
    {
      "campaignId": "SAMPLE-CAMPAIN-ID", 
      "settings": {
        "xsi_type": "TargetingSetting", 
        "type": "TARGET_LIST_SETTING", 
        "targetAll": "ACTIVE"
      }
    }, 
    {
      "campaignId": "SAMPLE-CAMPAIN-ID", 
      "settings": {
        "xsi_type": "TargetingSetting", 
        "type": "TARGET_LIST_SETTING", 
        "targetAll": "DEACTIVE"
      }
    }
  ]
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "ListReturnValue.Type": "CampaignReturnValue", 
    "Operation.Type": "SET", 
    "values": [
      {
        "operationSucceeded": "true", 
        "campaign": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "campaignId": "SAMPLE-CAMPAIN-ID", 
          "campaignName": "STANDARD_MANUAL_CPC", 
          "userStatus": "ACTIVE", 
          "startDate": "20170701", 
          "endDate": "20371231", 
          "budget": {
            "period": "DAILY", 
            "amount": "10000", 
            "deliveryMethod": "STANDARD"
          }, 
          "biddingStrategyConfiguration": {
            "biddingStrategyType": "MANUAL_CPC"
          }, 
          "adServingOptimizationStatus": "CONVERSION_OPTIMIZE", 
          "settings": [
            {
              "xsi_type": "GeoTargetTypeSetting", 
              "type": "GEO_TARGET_TYPE_SETTING", 
              "positiveGeoTargetType": "DONT_CARE", 
              "negativeGeoTargetType": "LOCATION_OF_PRESENCE"
            }, 
            {
              "xsi_type": "TargetingSetting", 
              "type": "TARGET_LIST_SETTING", 
              "targetAll": "ACTIVE"
            }
          ], 
          "campaignType": "STANDARD", 
          "trackingUrl": "http://yahoo.co.jp?url={lpurl}&c={campaignid}&g={adgroupid}&a={creative}&type={site}&pid={id1}&vid={id2}", 
          "customParameters": {
            "parameters": [
              {
                "key": "site", 
                "value": "yahoo"
              }, 
              {
                "key": "id1", 
                "value": "1234"
              }, 
              {
                "key": "id2", 
                "value": "a7h59A98yu"
              }
            ]
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "campaign": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "campaignId": "SAMPLE-CAMPAIN-ID", 
          "campaignName": "IOS_MANUAL_CPC", 
          "userStatus": "ACTIVE", 
          "startDate": "20170701", 
          "endDate": "20371231", 
          "budget": {
            "period": "DAILY", 
            "amount": "10000", 
            "deliveryMethod": "STANDARD"
          }, 
          "biddingStrategyConfiguration": {
            "biddingStrategyType": "MANUAL_CPC"
          }, 
          "adServingOptimizationStatus": "OPTIMIZE", 
          "settings": [
            {
              "xsi_type": "GeoTargetTypeSetting", 
              "type": "GEO_TARGET_TYPE_SETTING", 
              "positiveGeoTargetType": "DONT_CARE", 
              "negativeGeoTargetType": "LOCATION_OF_PRESENCE"
            }, 
            {
              "xsi_type": "TargetingSetting", 
              "type": "TARGET_LIST_SETTING", 
              "targetAll": "DEACTIVE"
            }
          ], 
          "campaignType": "MOBILE_APP", 
          "appStore": "IOS", 
          "appId": "sampleAppId", 
          "trackingUrl": "http://yahoo.co.jp?url={lpurl}&c={campaignid}&g={adgroupid}&a={creative}&type={site}&pid={id1}&vid={id2}", 
          "customParameters": {
            "parameters": [
              {
                "key": "site", 
                "value": "yahoo"
              }, 
              {
                "key": "id1", 
                "value": "1234"
              }, 
              {
                "key": "id2", 
                "value": "a7h59A98yu"
              }
            ]
          }
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
