# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : AccountService
Operation: get
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/6.3/docs/en/api_reference/services/AccountService.md

Generated by 'api_reference_example_generator.py' using code template 'sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'AccountService'
OPERATION = 'get'
OPERAND = {
  "accountIds": [
    "SAMPLE-ACCOUNT-ID"
  ], 
  "accountTypes": "PREPAY", 
  "paging": {
    "startIndex": "0", 
    "numberResults": "1"
  }
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "totalNumEntries": "2", 
    "Page.Type": "AccountPage", 
    "values": [
      {
        "operationSucceeded": "true", 
        "account": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "accountName": "XXXXXXXXXXXXXX", 
          "accountType": "INVOICE", 
          "accountStatus": "SERVING", 
          "deliveryStatus": "ACTIVE", 
          "budget": {
            "amount": "1000000", 
            "limitChargeType": "SUM", 
            "startDate": "20091130", 
            "endDate": "20200120"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "account": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "accountName": "XXXXXXXXXXXXXX", 
          "accountType": "INVOICE", 
          "accountStatus": "CANCELED", 
          "deliveryStatus": "ACTIVE", 
          "budget": {
            "amount": "2000000", 
            "limitChargeType": "SUM", 
            "startDate": "20091031", 
            "endDate": "20100320"
          }
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
