# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : AuditLogService
Operation: get
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/201901/docs/en/api_reference/services/AuditLogService.md

Generated by 'api_reference_example_generator.py' using code template 'examples/sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'AuditLogService'
OPERATION = 'get'
OPERAND = {
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "jobIds": [
    "1111", 
    "1112"
  ], 
  "jobStatuses": [
    "SYSTEM_ERROR", 
    "COMPLETED", 
    "IN_PROGRESS", 
    "TIMEOUT"
  ], 
  "paging": {
    "startIndex": "1", 
    "numberResults": "10"
  }
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "totalNumEntries": "4", 
    "Page.Type": "AuditLogPage", 
    "values": [
      {
        "operationSucceeded": "true", 
        "job": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "jobId": "19771824", 
          "jobName": "Sample Audit Log", 
          "jobStatus": "IN_PROGRESS", 
          "eventSelector": {
            "entityType": "ALL", 
            "eventTypes": [
              "ADD", 
              "SET", 
              "REMOVE"
            ]
          }, 
          "dateRange": {
            "startDate": "20170701000000", 
            "endDate": "20170810235959"
          }, 
          "sourceType": "ALL", 
          "output": "CSV", 
          "encoding": "UTF_8", 
          "lang": "JA"
        }
      }, 
      {
        "operationSucceeded": "true", 
        "job": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "jobId": "222222", 
          "jobName": "Sample Audit Log2", 
          "jobStatus": "COMPLETED", 
          "downloadUrl": "https ://colo01.ss.yahooapis.jp/audit/V201901/download/XtuXVU2EbFtOg4qiJCos2FRMXLWTmulJXr4D9Ed1HVLBFrf2Wp3qHwgrVcswR65IHc7bJYsluuJqfGLdDsChrAh_mFtx.2OJlcFkpJ8vgEgygk3dnz6IFW376asnE9kK_z8zhFiL0hx7Tf7UhwtvPw0bYD_vt9Zy2vLBLkNRTeEjU0OrR4ydUg3PvPpg0nDXzbwH2B3xD37Qx.PN6_2tCKpvz5m8kWZOtudS2oeGJAYh95gcBF2Ng0Mi4ZlJoGmRcDNsq79eTW7lsSFj8q7ZT1benaYFE.KsJigCSNPJI0SyLc_neR6PR0t3cov3kNURju6CQY_FLXos45900v6jpAhqZg--", 
          "eventSelector": {
            "entityType": "ALL", 
            "eventTypes": [
              "ADD", 
              "SET", 
              "REMOVE"
            ]
          }, 
          "dateRange": {
            "startDate": "20170701000000", 
            "endDate": "20170810235959"
          }, 
          "sourceType": "ALL", 
          "output": "CSV", 
          "encoding": "UTF_8", 
          "lang": "JA"
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
