# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : FeedItemService
Operation: get
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/201901/docs/en/api_reference/services/FeedItemService.md

Generated by 'api_reference_example_generator.py' using code template 'examples/sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'FeedItemService'
OPERATION = 'get'
OPERAND = {
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "feedItemIds": [
    "200000001", 
    "200000002", 
    "200000003", 
    "200000004", 
    "200000005"
  ], 
  "placeholderTypes": [
    "QUICKLINK", 
    "CALLEXTENSION", 
    "AD_CUSTOMIZER", 
    "CALLOUT", 
    "STRUCTURED_SNIPPET"
  ], 
  "approvalStatuses": [
    "APPROVED", 
    "APPROVED_WITH_REVIEW", 
    "REVIEW", 
    "PRE_DISAPPROVED", 
    "POST_DISAPPROVED"
  ], 
  "paging": {
    "startIndex": "1", 
    "numberResults": "1000"
  }
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "totalNumEntries": "1", 
    "Page.Type": "FeedItemPage", 
    "values": [
      {
        "operationSucceeded": "true", 
        "feedItem": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "feedItemId": "200000001", 
          "feedItemTrackId": "300000001", 
          "approvalStatus": "APPROVED", 
          "trademarkStatus": "NO_RESTRICTION", 
          "invalidedTrademarks": "sample text trademark 1", 
          "feedItemAttribute": [
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "LINK_TEXT", 
              "feedAttributeValue": "quicklink feedItem."
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "ADVANCED_URL", 
              "feedAttributeValue": "http://www.yahoo.co.jp"
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "ADVANCED_MOBILE_URL", 
              "feedAttributeValue": "http://portal.mobile.yahoo.co.jp"
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "TRACKING_URL", 
              "feedAttributeValue": "http://yahoo.co.jp?url={lpurl}&c={campaignid}&g={adgroupid}&a={creative}&type={_site}&pid={_id1}&vid={_id2}"
            }
          ], 
          "placeholderType": "QUICKLINK", 
          "startDate": "20190118", 
          "endDate": "20190218", 
          "scheduling": {
            "schedules": {
              "dayOfWeek": "MONDAY", 
              "startHour": "14", 
              "startMinute": "ZERO", 
              "endHour": "15", 
              "endMinute": "FIFTEEN"
            }
          }, 
          "customParameters": {
            "parameters": [
              {
                "key": "site", 
                "value": "yahoo"
              }, 
              {
                "key": "id1", 
                "value": "1234"
              }, 
              {
                "key": "id2", 
                "value": "a7h59A98yu"
              }
            ]
          }, 
          "geoTargeting": {
            "geoTargetingRestriction": "NONE"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "feedItem": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "feedItemId": "200000002", 
          "feedItemTrackId": "0", 
          "approvalStatus": "APPROVED", 
          "feedItemAttribute": [
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "LINK_TEXT", 
              "feedAttributeValue": "update quicklink feedItem."
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "ADVANCED_URL", 
              "feedAttributeValue": "http://www.yahoo.co.jp"
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "ADVANCED_MOBILE_URL", 
              "feedAttributeValue": "http://portal.mobile.yahoo.co.jp"
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "TRACKING_URL", 
              "feedAttributeValue": "http://yahoo.co.jp?url={lpurl}&c={campaignid}&g={adgroupid}&a={creative}&type={_site}&pid={_id1}&vid={_id2}"
            }, 
            {
              "xsi_type": "MultipleFeedItemAttribute", 
              "placeholderField": "ADDITIONAL_ADVANCED_URLS", 
              "feedAttributeValues": [
                {
                  "feedAttributeValue": "http://www.yahoo.co.jp/lp1/"
                }, 
                {
                  "feedAttributeValue": "http://www.yahoo.co.jp/lp2/"
                }, 
                {
                  "feedAttributeValue": "http://www.yahoo.co.jp/lp3/"
                }
              ]
            }, 
            {
              "xsi_type": "MultipleFeedItemAttribute", 
              "placeholderField": "ADDITIONAL_ADVANCED_MOBILE_URLS", 
              "feedAttributeValues": [
                {
                  "feedAttributeValue": "http://portal.mobile.yahoo.co.jp/lp1/"
                }, 
                {
                  "feedAttributeValue": "http://portal.mobile.yahoo.co.jp/lp2/"
                }, 
                {
                  "feedAttributeValue": "http://portal.mobile.yahoo.co.jp/lp3/"
                }
              ]
            }
          ], 
          "placeholderType": "QUICKLINK", 
          "startDate": "20190118", 
          "endDate": "20190218", 
          "scheduling": {
            "schedules": {
              "dayOfWeek": "MONDAY", 
              "startHour": "14", 
              "startMinute": "ZERO", 
              "endHour": "15", 
              "endMinute": "FIFTEEN"
            }
          }, 
          "reviewCustomParameters": {
            "parameters": [
              {
                "key": "site", 
                "value": "yahoo"
              }, 
              {
                "key": "id1", 
                "value": "1234"
              }, 
              {
                "key": "id2", 
                "value": "a7h59A98yu"
              }
            ]
          }, 
          "geoTargeting": {
            "geoTargetingRestriction": "NONE"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "feedItem": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "feedItemId": "200000003", 
          "feedItemTrackId": "0", 
          "approvalStatus": "REVIEW", 
          "feedItemAttribute": {
            "xsi_type": "SimpleFeedItemAttribute", 
            "placeholderField": "CALL_PHONE_NUMBER", 
            "feedAttributeValue": "0120-111-222"
          }, 
          "placeholderType": "CALLEXTENSION", 
          "devicePreference": "SMART_PHONE", 
          "startDate": "20190118", 
          "endDate": "20190218", 
          "scheduling": {
            "schedules": {
              "dayOfWeek": "MONDAY", 
              "startHour": "14", 
              "startMinute": "ZERO", 
              "endHour": "15", 
              "endMinute": "FIFTEEN"
            }
          }, 
          "geoTargeting": {
            "geoTargetingRestriction": "NONE"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "feedItem": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "feedItemId": "200000004", 
          "feedItemTrackId": "0", 
          "approvalStatus": "REVIEW", 
          "feedItemAttribute": {
            "xsi_type": "SimpleFeedItemAttribute", 
            "placeholderField": "CALLOUT_TEXT", 
            "feedAttributeValue": "callout text."
          }, 
          "placeholderType": "CALLOUT", 
          "startDate": "20190118", 
          "endDate": "20190218", 
          "scheduling": {
            "schedules": {
              "dayOfWeek": "MONDAY", 
              "startHour": "14", 
              "startMinute": "ZERO", 
              "endHour": "15", 
              "endMinute": "FIFTEEN"
            }
          }, 
          "geoTargeting": {
            "geoTargetingRestriction": "NONE"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "feedItem": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "feedFolderId": "300000001", 
          "feedItemId": "200000005", 
          "feedItemTrackId": "0", 
          "approvalStatus": "REVIEW", 
          "feedItemAttribute": [
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "AD_CUSTOMIZER_STRING", 
              "feedAttributeId": "1", 
              "feedAttributeValue": "test"
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "AD_CUSTOMIZER_DATE", 
              "feedAttributeId": "2", 
              "feedAttributeValue": "20151231 235959"
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "AD_CUSTOMIZER_INTEGER", 
              "feedAttributeId": "3", 
              "feedAttributeValue": "1234567890"
            }, 
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "AD_CUSTOMIZER_PRICE", 
              "feedAttributeId": "4", 
              "feedAttributeValue": "9,999,999.99"
            }
          ], 
          "placeholderType": "AD_CUSTOMIZER", 
          "startDate": "20190118", 
          "endDate": "20190218", 
          "scheduling": {
            "schedules": {
              "dayOfWeek": "MONDAY", 
              "startHour": "14", 
              "startMinute": "ZERO", 
              "endHour": "15", 
              "endMinute": "FIFTEEN"
            }
          }, 
          "targetingCampaign": {
            "targetingCampaignId": "400000001"
          }, 
          "targetingAdGroup": {
            "targetingAdGroupId": "500000001"
          }, 
          "targetingKeyword": {
            "targetingKeywordId": "600000001", 
            "text": "test keyword", 
            "matchType": "EXACT"
          }, 
          "geoTargeting": {
            "targetId": "JP-01-0010", 
            "type": "LOCATION", 
            "geoTargetingRestriction": "LOCATION_OF_PRESENCE"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "feedItem": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "feedItemId": "200000001", 
          "feedItemTrackId": "0", 
          "approvalStatus": "REVIEW", 
          "feedItemAttribute": [
            {
              "xsi_type": "SimpleFeedItemAttribute", 
              "placeholderField": "STRUCTURED_SNIPPET_HEADER", 
              "feedAttributeValue": "Brands"
            }, 
            {
              "xsi_type": "MultipleFeedItemAttribute", 
              "placeholderField": "STRUCTURED_SNIPPET_VALUES", 
              "feedAttributeValues": [
                {
                  "feedAttributeValue": "NIKE"
                }, 
                {
                  "feedAttributeValue": "ADIDAS"
                }, 
                {
                  "feedAttributeValue": "PUMA"
                }
              ]
            }
          ], 
          "placeholderType": "STRUCTURED_SNIPPET", 
          "startDate": "20190118", 
          "endDate": "20190218", 
          "scheduling": {
            "schedules": {
              "dayOfWeek": "MONDAY", 
              "startHour": "14", 
              "startMinute": "ZERO", 
              "endHour": "15", 
              "endMinute": "FIFTEEN"
            }
          }
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
