# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : ReportService
Operation: get
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/201901/docs/en/api_reference/services/ReportService.md

Generated by 'api_reference_example_generator.py' using code template 'examples/sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'ReportService'
OPERATION = 'get'
OPERAND = {
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "reportIds": [
    "1111", 
    "1112"
  ], 
  "reportTypes": [
    "ACCOUNT", 
    "CAMPAIGN", 
    "ADGROUP", 
    "AD", 
    "KEYWORDS", 
    "SEARCH_QUERY", 
    "GEO", 
    "FEED_ITEM", 
    "GEO_TARGET", 
    "SCHEDULE_TARGET", 
    "BID_STRATEGY", 
    "AD_CUSTOMIZERS", 
    "TARGET_LIST", 
    "LANDING_PAGE_URL"
  ], 
  "reportJobStatuses": [
    "WAIT", 
    "COMPLETED", 
    "IN_PROGRESS", 
    "FAILED"
  ], 
  "paging": {
    "startIndex": "1", 
    "numberResults": "10"
  }
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "totalNumEntries": "4", 
    "Page.Type": "ReportPage", 
    "values": [
      {
        "operationSucceeded": "true", 
        "reportRecord": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "reportId": "1111", 
          "reportName": "Sample LANDING_PAGE_URL Report", 
          "reportJobStatus": "COMPLETED", 
          "requestTime": "2017/11/27 14:32:48", 
          "completeTime": "2017/11/27 14:33:20", 
          "reportDownloadURL": "https://ss.yahooapis.jp/report/V201901/download/3CRAGObSahcIylBoDZS5ftx7qS4VM5jSHqs77QZqmpBFnJFP2jvKe3Dy72UEX3InsUoShWXa3YcX3AmbtqxGco6B"
        }
      }, 
      {
        "operationSucceeded": "true", 
        "reportRecord": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "reportId": "1112", 
          "reportName": "Sample LANDING_PAGE_URL Report2", 
          "reportJobStatus": "FAILED", 
          "reportJobErrorDetail": "INTERNAL_ERROR", 
          "requestTime": "2017/11/27 14:32:48"
        }
      }, 
      {
        "operationSucceeded": "true", 
        "reportRecord": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "reportId": "1113", 
          "reportName": "Sample LANDING_PAGE_URL Report3", 
          "reportJobStatus": "IN_PROGRESS", 
          "requestTime": "2017/11/27 14:32:48"
        }
      }, 
      {
        "operationSucceeded": "true", 
        "reportRecord": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "reportId": "1114", 
          "reportName": "Sample LANDING_PAGE_URL Report3", 
          "reportJobStatus": "WAIT", 
          "requestTime": "2017/11/27 14:32:48"
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
