# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : ReportDefinitionService
Operation: getReportFields
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/6.3/docs/en/api_reference/services/ReportDefinitionService.md

Generated by 'api_reference_example_generator.py' using code template 'sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'ReportDefinitionService'
OPERATION = 'getReportFields'
# Correction to auto-generated code
# OPERAND = {
#  "reportType": "LANDING_PAGE_URL"
# }
OPERAND = "LANDING_PAGE_URL"

"""
SAMPLE RESPONSE = {
  "rval": {
    "operationSucceeded": "true", 
    "fields": [
      {
        "fieldName": "CAMPAIGN_ID", 
        "displayFieldNameJA": "\u30ad\u30e3\u30f3\u30da\u30fc\u30f3ID", 
        "displayFieldNameEN": "CampaignID", 
        "fieldType": "LONG", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "ADGROUP_ID", 
        "displayFieldNameJA": "\u5e83\u544a\u30b0\u30eb\u30fc\u30d7ID", 
        "displayFieldNameEN": "Ad Group ID", 
        "fieldType": "LONG", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "ADGROUP_ID", 
          "CAMPAIGN_NAME"
        ]
      }, 
      {
        "fieldName": "CAMPAIGN_NAME", 
        "displayFieldNameJA": "\u30ad\u30e3\u30f3\u30da\u30fc\u30f3\u540d", 
        "displayFieldNameEN": "Campaign Name", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_NAME", 
          "AD_NAME"
        ]
      }, 
      {
        "fieldName": "ADGROUP_NAME", 
        "displayFieldNameJA": "\u5e83\u544a\u30b0\u30eb\u30fc\u30d7\u540d", 
        "displayFieldNameEN": "Ad Group Name", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "AD_NAME", 
          "TITLE"
        ]
      }, 
      {
        "fieldName": "COST", 
        "displayFieldNameJA": "\u30b3\u30b9\u30c8", 
        "displayFieldNameEN": "Cost", 
        "fieldType": "LONG", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "DESCRIPTION", 
          "COST"
        ]
      }, 
      {
        "fieldName": "IMPS", 
        "displayFieldNameJA": "\u30a4\u30f3\u30d7\u30ec\u30c3\u30b7\u30e7\u30f3\u6570", 
        "displayFieldNameEN": "Impressions", 
        "fieldType": "LONG", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "CLICKS", 
        "displayFieldNameJA": "\u30af\u30ea\u30c3\u30af\u6570", 
        "displayFieldNameEN": "Clicks", 
        "fieldType": "LONG", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "CLICK_RATE", 
        "displayFieldNameJA": "\u30af\u30ea\u30c3\u30af\u7387", 
        "displayFieldNameEN": "CTR", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "AVG_CPM", 
        "displayFieldNameJA": "\u5e73\u5747CPM", 
        "displayFieldNameEN": "Avg. CPM", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "AVG_CPC", 
        "displayFieldNameJA": "\u5e73\u5747CPC", 
        "displayFieldNameEN": "Avg. CPC", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "AVG_DELIVER_RANK", 
        "displayFieldNameJA": "\u5e73\u5747\u63b2\u8f09\u9806\u4f4d", 
        "displayFieldNameEN": "Avg. Position", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "REVENUE", 
        "displayFieldNameJA": "\u5408\u8a08\u58f2\u4e0a\u91d1\u984d", 
        "displayFieldNameEN": "Total Revenue", 
        "fieldType": "LONG", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "UNIQUE_CONVERSION", 
        "displayFieldNameJA": "\u30e6\u30cb\u30fc\u30af\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u6570", 
        "displayFieldNameEN": "Unique Conversions", 
        "fieldType": "LONG", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "UNIQUE_CONVERSION_RATE", 
        "displayFieldNameJA": "\u30e6\u30cb\u30fc\u30af\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u7387", 
        "displayFieldNameEN": "Unique Conversion Rate", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "REVENUE_UNIQUE_CONVERSION", 
        "displayFieldNameJA": "\u58f2\u4e0a/\u30e6\u30cb\u30fc\u30af\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u6570", 
        "displayFieldNameEN": "Revenue / Unique Conversions", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "REVENUE_CONVERSION", 
        "displayFieldNameJA": "\u58f2\u4e0a/\u7dcf\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u6570", 
        "displayFieldNameEN": "Revenue / Total Conversions", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "CONVERSION", 
        "displayFieldNameJA": "\u7dcf\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u6570", 
        "displayFieldNameEN": "Total Conversions", 
        "fieldType": "LONG", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "CONVERSION_RATE", 
        "displayFieldNameJA": "\u7dcf\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u7387", 
        "displayFieldNameEN": "Total Conversion Rate", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "COST_UNIQUE_CONVERSION", 
        "displayFieldNameJA": "\u30b3\u30b9\u30c8/\u30e6\u30cb\u30fc\u30af\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u6570", 
        "displayFieldNameEN": "Cost / Unique Conversions", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "CPA", 
        "displayFieldNameJA": "\u30b3\u30b9\u30c8/\u7dcf\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u6570", 
        "displayFieldNameEN": "Cost / Total Conversions", 
        "fieldType": "DOUBLE", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "TRACKING_URL", 
        "displayFieldNameJA": "\u30c8\u30e9\u30c3\u30ad\u30f3\u30b0URL", 
        "displayFieldNameEN": "Tracking URL", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "LANDING_PAGE_URL", 
        "displayFieldNameJA": "\u6700\u7d42\u30ea\u30f3\u30af\u5148URL", 
        "displayFieldNameEN": "Landing Page URL", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "NETWORK", 
        "displayFieldNameJA": "\u5e83\u544a\u63b2\u8f09\u65b9\u5f0f\u306e\u6307\u5b9a", 
        "displayFieldNameEN": "Network", 
        "fieldType": "ENUM", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "DEVICE", 
        "displayFieldNameJA": "\u30c7\u30d0\u30a4\u30b9", 
        "displayFieldNameEN": "Device", 
        "fieldType": "ENUM", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "DAY", 
        "displayFieldNameJA": "\u65e5", 
        "displayFieldNameEN": "Day", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "DAY_OF_WEEK", 
        "displayFieldNameJA": "\u66dc\u65e5", 
        "displayFieldNameEN": "Day of week", 
        "fieldType": "ENUM", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "QUARTER", 
        "displayFieldNameJA": "\u56db\u534a\u671f", 
        "displayFieldNameEN": "Quarter", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "YEAR", 
        "displayFieldNameJA": "\u5e74\u9593", 
        "displayFieldNameEN": "Year", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "MONTH", 
        "displayFieldNameJA": "\u6bce\u6708", 
        "displayFieldNameEN": "Month", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "MONTH_OF_YEAR", 
        "displayFieldNameJA": "\u6708", 
        "displayFieldNameEN": "Month of Year", 
        "fieldType": "ENUM", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "WEEK", 
        "displayFieldNameJA": "\u6bce\u9031", 
        "displayFieldNameEN": "Week", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "OBJECT_OF_CONVERSION_TRACKING", 
        "displayFieldNameJA": "\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u6e2c\u5b9a\u306e\u76ee\u7684", 
        "displayFieldNameEN": "Objective of Conversion Tracking", 
        "fieldType": "ENUM", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }, 
      {
        "fieldName": "CONVERSION_NAME", 
        "displayFieldNameJA": "\u30b3\u30f3\u30d0\u30fc\u30b8\u30e7\u30f3\u540d", 
        "displayFieldNameEN": "Conversion Name", 
        "fieldType": "STRING", 
        "canSelect": "true", 
        "canFilter": "true", 
        "impossibleCombinationFields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID"
        ]
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
