# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : ReportDefinitionService
Operation: get
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/201901/docs/en/api_reference/services/ReportDefinitionService.md

Generated by 'api_reference_example_generator.py' using code template 'examples/sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'ReportDefinitionService'
OPERATION = 'get'
OPERAND = {
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "reportIds": [
    "1111", 
    "1111"
  ], 
  "paging": {
    "startIndex": "1", 
    "numberResults": "10"
  }
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "totalNumEntries": "2", 
    "Page.Type": "ReportDefinitionPage", 
    "values": {
      "operationSucceeded": "true", 
      "reportDefinition": {
        "reportId": "1111", 
        "reportName": "Sample LANDING_PAGE_URL Report", 
        "reportType": "LANDING_PAGE_URL", 
        "dateRangeType": "CUSTOM_DATE", 
        "dateRange": {
          "startDate": "20160101", 
          "endDate": "20161231"
        }, 
        "fields": [
          "CAMPAIGN_ID", 
          "ADGROUP_ID", 
          "CAMPAIGN_NAME", 
          "ADGROUP_NAME", 
          "COST", 
          "IMPS", 
          "CLICKS", 
          "CLICK_RATE", 
          "AVG_CPM", 
          "AVG_CPC", 
          "AVG_DELIVER_RANK", 
          "REVENUE", 
          "UNIQUE_CONVERSION", 
          "UNIQUE_CONVERSION_RATE", 
          "REVENUE_UNIQUE_CONVERSION", 
          "TRACKING_URL", 
          "CUSTOM_PARAMETERS", 
          "LANDING_PAGE_URL", 
          "NETWORK", 
          "DEVICE", 
          "DAY", 
          "DAY_OF_WEEK", 
          "QUARTER", 
          "YEAR", 
          "MONTH", 
          "MONTH_OF_YEAR", 
          "WEEK", 
          "OBJECT_OF_CONVERSION_TRACKING", 
          "CONVERSION_NAME"
        ], 
        "sortFields": {
          "type": "ASC", 
          "field": "CLICKS"
        }, 
        "filters": [
          {
            "field": "TRACKING_URL", 
            "operator": "IN", 
            "value": [
              "http://yahoo.co.jp", 
              "http://marketing.yahoo.co.jp", 
              "http://promotionalads.yahoo.co.jp"
            ]
          }, 
          {
            "field": "IMPS", 
            "operator": "GREATER_THAN", 
            "value": "0"
          }, 
          {
            "field": "CAMPAIGN_ID", 
            "operator": "IN", 
            "value": [
              "200000001", 
              "200000002", 
              "200000003", 
              "200000003", 
              "200000004", 
              "200000005"
            ]
          }
        ], 
        "isTemplate": "FALSE", 
        "intervalType": "SPECIFYDAY", 
        "specifyDay": "28", 
        "format": "CSV", 
        "encode": "UTF-8", 
        "language": "EN", 
        "compress": "NONE", 
        "includeZeroImpressions": "FALSE", 
        "includeDeleted": "FALSE"
      }
    }
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
