# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : ConversionTrackerService
Operation: mutate (ADD)
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/6.5/docs/en/api_reference/services/ConversionTrackerService.md

Generated by 'api_reference_example_generator.py' using code template 'sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'ConversionTrackerService'
OPERATION = 'mutate (ADD)'
OPERAND = {
  "operator": "ADD", 
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "operand": [
    {
      "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
      "xsi_type": "WebConversion", 
      "conversionTrackerName": "WebConversion", 
      "status": "ENABLED", 
      "category": "DEFAULT", 
      "conversionTrackerType": "WEB_CONVERSION", 
      "markupLanguage": "HTML", 
      "trackingCodeType": "WEBPAGE", 
      "crossDeviceConversionFlag": "TRUE"
    }, 
    {
      "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
      "xsi_type": "AppConversion", 
      "conversionTrackerName": "AppConversion", 
      "status": "ENABLED", 
      "category": "DOWNLOAD", 
      "conversionTrackerType": "APP_CONVERSION", 
      "appId": "abc_1234", 
      "appPlatform": "ANDROID_MARKET", 
      "appConversionType": "DOWNLOAD"
    }
  ]
}

"""
SAMPLE RESPONSE = {
  "@xmlns": "http://ss.yahooapis.jp/V6", 
  "rval": {
    "ListReturnValue.Type": "AccountTrackingUrlReturnValue", 
    "Operation.Type": "ADD", 
    "values": [
      {
        "operationSucceeded": "true", 
        "conversionTracker": {
          "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
          "xsi_type": "AppConversion", 
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "conversionTrackerId": "1193198", 
          "conversionTrackerName": "APP_ANDROID_IN_APP_PURCHASE_CONVERSION_TRACKER", 
          "status": "ENABLED", 
          "category": "DEFAULT", 
          "conversions": "0", 
          "conversionValue": "0", 
          "allConversions": "10", 
          "conversionTrackerType": "APP_CONVERSION", 
          "userRevenueValue": "100", 
          "countingType": "MANY_PER_CLICK", 
          "excludeFromBidding": "TRUE", 
          "measurementPeriod": "30", 
          "appPlatform": "ANDROID_MARKET", 
          "appConversionType": "IN_APP_PURCHASE", 
          "snippetId": "1000661", 
          "snippetLabel": "XXXXXXXXXXXXXXXXXX"
        }
      }, 
      {
        "operationSucceeded": "true", 
        "conversionTracker": {
          "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
          "xsi_type": "AppConversion", 
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "conversionTrackerId": "1193197", 
          "conversionTrackerName": "APP_ANDROID_FIRST_OPEN_CONVERSION_TRACKER", 
          "status": "ENABLED", 
          "category": "DOWNLOAD", 
          "conversions": "0", 
          "conversionValue": "0", 
          "allConversions": "20", 
          "conversionTrackerType": "APP_CONVERSION", 
          "userRevenueValue": "1", 
          "countingType": "ONE_PER_CLICK", 
          "excludeFromBidding": "TRUE", 
          "measurementPeriod": "7", 
          "appId": "abc_1234", 
          "appPlatform": "ANDROID_MARKET", 
          "appConversionType": "FIRST_OPEN", 
          "snippetId": "1000661", 
          "snippetLabel": "XXXXXXXXXXXXXXXXXX", 
          "appPostbackUrl": {
            "url": ">http://yahoo.co.jp?advertising_id={adid}&amp;lat={lat}"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "conversionTracker": {
          "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
          "xsi_type": "AppConversion", 
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "conversionTrackerId": "1193196", 
          "conversionTrackerName": "APP_ANDROID_DOWNLOAD_CONVERSION_TRACKER", 
          "status": "ENABLED", 
          "category": "DOWNLOAD", 
          "conversions": "20", 
          "conversionValue": "20", 
          "allConversions": "20", 
          "conversionTrackerType": "APP_CONVERSION", 
          "userRevenueValue": "1", 
          "countingType": "ONE_PER_CLICK", 
          "excludeFromBidding": "FALSE", 
          "measurementPeriod": "90", 
          "appId": "abc_1234", 
          "appPlatform": "ANDROID_MARKET", 
          "appConversionType": "DOWNLOAD"
        }
      }, 
      {
        "operationSucceeded": "true", 
        "conversionTracker": {
          "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
          "xsi_type": "WebConversion", 
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "conversionTrackerId": "1193194", 
          "conversionTrackerName": "WEB_CONVERSION_TRACKER", 
          "status": "ENABLED", 
          "category": "PAGE_VIEW", 
          "conversionTrackerType": "WEB_CONVERSION", 
          "userRevenueValue": "100", 
          "countingType": "MANY_PER_CLICK", 
          "excludeFromBidding": "FALSE", 
          "measurementPeriod": "30", 
          "snippet": "&amp;lt;!-- Yahoo Code for your Conversion Page --&amp;gt;\n&amp;lt;script type=\"text/javascript\"&amp;gt;\n    /* &amp;lt;![CDATA[ */\n    var yahoo_conversion_id = 1000661;\n    var yahoo_conversion_label = \"XXXXXXXXXXXXXXXXXX\";\n    var yahoo_conversion_value = 100;\n    /* ]]&amp;gt; */\n&amp;lt;/script&amp;gt;\n&amp;lt;script type=\"text/javascript\" src=\"//s.yimg.jp/images/listing/tool/cv/conversion.js\"&amp;gt;\n&amp;lt;/script&amp;gt;\n&amp;lt;noscript&amp;gt;\n    &amp;lt;div style=\"display:inline;\"&amp;gt;\n        &amp;lt;img height=\"1\" width=\"1\" style=\"border-style:none;\" alt=\"\" src=\"//b91.yahoo.co.jp/pagead/conversion/1000661/?value=100&amp;amp;label=XXXXXXXXXXXXXXXXXX&amp;amp;guid=ON&amp;amp;script=0&amp;amp;disvt=true\"/&amp;gt;\n    &amp;lt;/div&amp;gt;\n&amp;lt;/noscript&amp;gt;", 
          "markupLanguage": "HTML", 
          "trackingCodeType": "WEBPAGE", 
          "crossDeviceConversionFlag": "TRUE"
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
