# Copyright 2017 Become Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example code for
Service : BiddingStrategyService
Operation: mutate (REMOVE)
API Reference: https://github.com/yahoojp-marketing/sponsored-search-api-documents/blob/201901/docs/en/api_reference/services/BiddingStrategyService.md

Generated by 'api_reference_example_generator.py' using code template 'examples/sample_template.py.template'
"""

import logging
import json

from yahooads import promotionalads

logging.basicConfig(level=logging.INFO)
# logging.getLogger('suds.client').setLevel(logging.DEBUG)
# logging.getLogger('suds.transport').setLevel(logging.DEBUG)


SERVICE = 'BiddingStrategyService'
OPERATION = 'mutate (REMOVE)'
OPERAND = {
  "operator": "REMOVE", 
  "accountId": "SAMPLE-ACCOUNT-ID", 
  "operand": [
    {
      "biddingStrategyId": "20001"
    }, 
    {
      "biddingStrategyId": "20002"
    }, 
    {
      "biddingStrategyId": "20003"
    }, 
    {
      "biddingStrategyId": "20004"
    }, 
    {
      "biddingStrategyId": "20005"
    }
  ]
}

"""
SAMPLE RESPONSE = {
  "rval": {
    "ListReturnValue.Type": "BiddingStrategyReturnValue", 
    "Operation.Type": "REMOVE", 
    "values": [
      {
        "operationSucceeded": "true", 
        "biddingStrategy": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "biddingStrategyId": "20002", 
          "biddingStrategyName": "PageOnePromotedBiddingScheme", 
          "biddingStrategyType": "PAGE_ONE_PROMOTED", 
          "biddingScheme": {
            "xsi_type": "PageOnePromotedBiddingScheme", 
            "biddingStrategyType": "PAGE_ONE_PROMOTED", 
            "targetPositionType": "PAGE_ONE_PROMOTED", 
            "bidCeiling": "2", 
            "bidMultiplier": "0.2", 
            "bidChangesForRaisesOnly": "DEACTIVE", 
            "raiseBidWhenBudgetConstrained": "DEACTIVE", 
            "raiseBidWhenLowQualityScore": "DEACTIVE"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "biddingStrategy": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "biddingStrategyId": "20003", 
          "biddingStrategyName": "TargetCpaBiddingScheme", 
          "biddingStrategyType": "TARGET_CPA", 
          "biddingScheme": {
            "xsi_type": "TargetCpaBiddingScheme", 
            "biddingStrategyType": "TARGET_CPA", 
            "targetCpa": "11111111", 
            "bidCeiling": "100", 
            "bidFloor": "10"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "biddingStrategy": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "biddingStrategyId": "20004", 
          "biddingStrategyName": "TargetSpendBiddingScheme", 
          "biddingStrategyType": "TARGET_SPEND", 
          "biddingScheme": {
            "xsi_type": "TargetSpendBiddingScheme", 
            "biddingStrategyType": "TARGET_SPEND", 
            "bidCeiling": "2", 
            "spendTarget": "10"
          }
        }
      }, 
      {
        "operationSucceeded": "true", 
        "biddingStrategy": {
          "accountId": "SAMPLE-ACCOUNT-ID", 
          "biddingStrategyId": "20005", 
          "biddingStrategyName": "TargetRoasBiddingScheme", 
          "biddingStrategyType": "TARGET_ROAS", 
          "biddingScheme": {
            "xsi_type": "TargetRoasBiddingScheme", 
            "biddingStrategyType": "TARGET_ROAS", 
            "targetRoas": "100.0", 
            "bidCeiling": "3000", 
            "bidFloor": "1"
          }
        }
      }
    ]
  }
}
"""


def main():
    client = promotionalads.PromotionalAdsClient.LoadFromConfiguration()
    service = client.GetService(SERVICE)
    print("REQUEST : {}.{}\n{}".format(SERVICE, OPERATION, json.dumps(OPERAND, indent=2)))
    try:
        if OPERATION == "get":
            response = service.get(OPERAND)
        elif OPERATION.startswith("get"):
            get_method = getattr(service, OPERATION)
            response = get_method(OPERAND)
        elif OPERATION.startswith("mutate"):
            response = service.mutate(OPERAND)
        else:
            raise("Unknown Operation '{}'".format(OPERATION))
        print("RESPONSE :\n{}".format(response))
    except Exception as e:
        print("Exception at '{}' operations \n{}".format(SERVICE, e))
        raise e


if __name__ == '__main__':
    main()
